name: push
on:
  push:
    branches:
    - master
jobs:
#Spellcheck Action
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Issue Checklist Checker
      uses: adamzolyak/checklist-checker-action@2.0.0 