name: push
on:
  push:
    branches:
    - master
jobs:
#Spellcheck Action
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Spellcheck Action
      uses: rojopolis/spellcheck-github-actions@0.2.0